### ISSUE TITLE
impossibile aprire client

### ISSUE THREAD

**Issue by ATLANCTIX4** [Criper98/DOSrat#3]
ho esportato il client con una chiavetta sul mio pc, ho tolto l'antivirus, ma quando vado per aprire, mi dice che è impossibile eseguire il file, poiché non ho digitato il nome corretto

**Comment by Criper98** [comment]
Sei sicuro di avere scritto il nome del Client correttamente quando lo hai creato dal server?
Ti ricordo che non devono esserci spazi, e devi mettere il ".exe" alla fine.
