### ISSUE TITLE
Non riesco ad eseguire il client.

### ISSUE THREAD

**Issue by Medy1** [Criper98/DOSrat#4]
**Descrivi il bug**
Praticamente ho provato a mandare il client ad un mio amico (quando ho fatto il client senza spazi)glielo mandato ed quando lo ha installato ha dato il concesso anche se presente antivirus, lo ha messo nel desktop e lo ha eseguito. L'antivirus ha chiesto se poteva essere consentito nel dispositivo, metto consenti e in teoria posso controllare il suo pc ma non mi da niente riguardante lui, in poche parole, il file appena eseguito non me lo ha trovato.

**Su che piattaforma è avvenuto il bug?**
Windows

**In che versione era il programma?**
1.14

**Commenti aggiuntivi**
/

**Comment by Medy1** [comment]
Scusa, versione 1.15

**Comment by Criper98** [comment]
L'antivirus andrebbe disabilitato completamente perché anche se aggiungi il Client sul desktop come eccezione quando poi esegui il Client il programma verrà bloccato lo stesso dall'antivirus perché il "vero" Client che si connette al Server non è nel desktop ma in una cartella semi nascosta in cui il Client ci si copia-incolla per risultare più "nascosto". Fammi sapere se disattivando l'antivirus riesci a risolvere o se ti da ancora problemi!
